services:
  seanime:
    image: ju1js/seanime:latest
    container_name: seanime
    environment:
      - SEANIME_SERVER_HOST=0.0.0.0
      - SEANIME_SERVER_PORT=43211
    ports:
      - "43211:43211"
    volumes:
      - ./config/seanime:/home/seanime/.config/Seanime
      - /mnt/series/anime:/anime
    restart: unless-stopped